# Generated by Django 4.2 on 2023-04-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Qustions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("content", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=50)),
                ("no1", models.CharField(max_length=50)),
                ("no2", models.CharField(max_length=50)),
                ("no3", models.CharField(max_length=50)),
                ("no4", models.CharField(max_length=50)),
            ],
        ),
    ]
