# Generated by Django 4.2 on 2023-04-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_qustions_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qustions",
            name="answer",
            field=models.PositiveIntegerField(),
        ),
    ]
