# Generated by Django 4.2 on 2023-04-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ozers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ozer",
            name="img",
        ),
        migrations.RemoveField(
            model_name="ozer",
            name="name",
        ),
        migrations.AddField(
            model_name="ozer",
            name="answers",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ozer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ozer",
            name="nickname",
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ozer",
            name="score",
            field=models.PositiveIntegerField(blank=True, default=0, max_length=3),
        ),
    ]
