# Generated by Django 4.2 on 2023-04-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ozers", "0002_remove_ozer_img_remove_ozer_name_ozer_answers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ozer",
            name="score",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
