# Generated by Django 4.2 on 2023-04-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0001_initial"),
        ("ozers", "0003_alter_ozer_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="TotalOzer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, unique=True)),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="list.list"
                    ),
                ),
            ],
        ),
    ]
