# Generated by Django 4.2 on 2023-05-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ozers", "0005_ozer_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="ozer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
